[tool.poetry]
name = "v2-rebalance-dashboard"
version = "0.1.0"
description = ""
authors = ["parkerburchett <parkerburchett@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter = "^1.0.0"
matplotlib = "^3.9.1"
pandas = "^2.2.2"
plotly = "^5.23.0"
black = {extras = ["jupyter"], version = "^24.8.0"}
multicall = "^0.9.0"

[tool.black]
# not working properly
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
