name: Fetch Exit Liquidity Swap Quotes

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 0 * * *" # midnight UTC daily (5pm pst)

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOTENV_BLOB: ${{ secrets.CI_DOT_ENV_FILE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true 

      - uses: actions/cache@v4
        with:
          path: |
            ./.venv
            ~/.cache/pypoetry
          key: poetry-3.10-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-3.10-${{ runner.os }}-

      - name: Create .env file from github secret
        shell: bash
        run: |
          umask 177
          printf '%s' "$DOTENV_BLOB" > .env

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run fetch exit liquidity quotes script
        run: poetry run fetch-exit-liqudity-quotes
        


