name: Fetch Exit Liquidity Swap Quotes

on:
  workflow_dispatch: 
  schedule:
    - cron: "40 0 * * *" # midnight + 40 UTC daily

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOTENV_BLOB: ${{ secrets.CI_DOT_ENV_FILE }}
      WHICH_DATABASE: MAIN_DATABASE_URL
      WHICH_ALCHEMY_URL: AUTOPOOL_DASHBOARD_CI_ALCHEMY_URL

    steps:
      - uses: actions/checkout@v4

      - name: Setup Poetry env and install dependencies
        uses: ./.github/actions/setup_env

      - name: Create .env from DOTENV_BLOB and append WHICH_* vars
        uses: ./.github/actions/create_dot_env_blob

      - name: Run fetch exit liquidity quotes script
        run: poetry run fetch-exit-liqudity-quotes
        


