name: Verify Can Read GitHub Secrets
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest 
    permissions:
      contents: read

    env:
      DOTENV_BLOB: ${{ secrets.FAKE_DOT_ENV }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Write DOTENV_BLOB to .env
        shell: bash
        run: |
          umask 177                                 
          printf '%s' "$DOTENV_BLOB" > .env

      - name: Install python-dotenv
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv

      - name: Verify Python can read it
        run: |
          python -c "from dotenv import dotenv_values; print(list(dotenv_values('.env').keys()))"
